data = iris
print("The Dimension of dataset:")
print(dim(data))
print("The Structure of dataset:")
print(str(data))
print("The Summary of dataset:")
print(summary(data))
print("The Standard deviation of dataset:")
print(sd(data$Sepal.Length))
print(sd(data$Sepal.Width))
print(sd(data$Petal.Length))
print(sd(data$Petal.Width))
print("The Quantile value of sepal width and Length:")
print(quantile(data$Sepal.Width))
print(quantile(data$Sepal.Length))
