print("First 10 Letters in lowercase:")
t = head(letters, 10)
print(t)
print("Last 10 Letters in Upper Case:")
t= tail(LETTERS, 10)
print(t)
print("Letters Between 22nd to 24th letters in Upper case:")
e=tail(LETTERS[22:24])
print(e)